name: CrashClaimEconomy
version: "${version}"
description: A claimblock economy for a modern advanced user oriented claiming system
author: Chasewhip
depend: [CrashClaim, ProtocolLib, CrashPayment]
softdepend: [PlaceholderAPI]
main: dev.whips.crashclaimeconomy.CrashClaimEconomy
api-version: 1.16
